/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package view;

import controller.Controller;
import java.io.FileWriter;
import java.io.IOException;
import java.time.LocalDate;
import java.time.LocalTime;
import java.util.List;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;
import model.Petugas;
import model.Ruta;

/**
 *
 * @author Bara
 */
public class BlokV extends javax.swing.JPanel {
    private Controller controller;

    /**
     * Creates new form BlokV
     */
    public BlokV(Controller controller) {
        this.controller = controller;
        initComponents();
    }
    
        public void populateTable() {
        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
        model.setRowCount(0);

        Petugas currentPetugas = controller.getCurrentPetugas();
        
        if (currentPetugas != null) {
            List<Ruta> rutas = controller.getAllRutaBySubSLS(currentPetugas.getKodeSubSLS());

            for (Ruta ruta : rutas) {
                Object[] row = {
                    ruta.getUrutKk(),
                    ruta.getNamakkLainnya(),
                    ruta.getAlamat(),
                    ruta.getUrutBtt(),
                    ruta.getJlhPetani(),
                    ruta.getKeberadaan(),
                    ruta.getJlhPengelolaan(),
                    ruta.getUrutRuta(),
                    ruta.getIdenKkKrt(),
                    ruta.getNamaKrt(),
                    ruta.getTanamanPangan(),
                    ruta.getHortikultura(),
                    ruta.getPerkebunan(),
                    ruta.getPeternakan(),
                    ruta.getPerikanan(),
                    ruta.getKehutanan(),
                    ruta.getJasaPertanian(),
                    ruta.getSubsektorUtama(),
                    ruta.getJumlahArtPertanian(),
                    ruta.getUrutRutaPertanian()
                };
                model.addRow(row);
            }
            List<Ruta> rutasBaru = controller.getAllRutaBaruBySubSLS(currentPetugas.getKodeSubSLS());
            
            for (Ruta ruta : rutasBaru) {
                Object[] row = {
                    ruta.getUrutKk(),
                    ruta.getNamakkLainnya(),
                    ruta.getAlamat(),
                    ruta.getUrutBtt(),
                    ruta.getJlhPetani(),
                    ruta.getKeberadaan(),
                    ruta.getJlhPengelolaan(),
                    ruta.getUrutRuta(),
                    ruta.getIdenKkKrt(),
                    ruta.getNamaKrt(),
                    ruta.getTanamanPangan(),
                    ruta.getHortikultura(),
                    ruta.getPerkebunan(),
                    ruta.getPeternakan(),
                    ruta.getPerikanan(),
                    ruta.getKehutanan(),
                    ruta.getJasaPertanian(),
                    ruta.getSubsektorUtama(),
                    ruta.getJumlahArtPertanian(),
                    ruta.getUrutRutaPertanian()
                };
                model.addRow(row);
            }
        } else {
            System.out.println("Current user is not set.");
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();

        setBackground(new java.awt.Color(0, 51, 153));

        jLabel1.setFont(new java.awt.Font("Helvetica", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("BLOK V. KETERANGAN KELUARGA / RUMAH TANGGA");

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "No. Urut Keluarga", "Nama KK/AK", "Alamat", "No. Urut BTT", "Jumlah Petani/Buruh", "Keberadaan Keluarga", "Jumlah Pengelola Pangan", "No. Urut Ruta", "Identifikasi KK/KRT", "Nama KRT", "Tanaman Pangan", "Hortikultura", "Perkebunan", "Peternakan", "Perikanan", "Kehutanan", "Jasa Pertanian", "Subsektor Utama", "Jumlah ART Petani", "No. Urut Ruta Usaha Pertanian"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.String.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.String.class, java.lang.Integer.class, java.lang.Integer.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        jButton1.setText("Ekspor CSV");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 900, Short.MAX_VALUE))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addGap(14, 14, 14))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 378, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButton1)
                .addContainerGap(12, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        int selectedRow = jTable1.getSelectedRow();
        if(jTable1.getSelectedRow() != -1){
            Object value = jTable1.getModel().getValueAt(selectedRow, 5);
            if (value==null || !"2".equals(value.toString())) {
                Petugas currentPetugas = controller.getCurrentPetugas();
                List<Ruta> rutas = controller.getAllRutaBySubSLS(currentPetugas.getKodeSubSLS());
                Ruta rutaTerpilih = rutas.get(jTable1.getSelectedRow());

                controller.showKeteranganRuta(rutaTerpilih);
            }else{
                JOptionPane.showMessageDialog(this, "Data rumah tangga baru tidak dapat di ubah", "Pesan", JOptionPane.WARNING_MESSAGE);
            }
        }
    }//GEN-LAST:event_jTable1MouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        JFileChooser fileChooser = new JFileChooser();
    fileChooser.setDialogTitle("Simpan Sebagai");
    
    int userSelection = fileChooser.showSaveDialog(null);
    if (userSelection == JFileChooser.APPROVE_OPTION) {
        String filePath = fileChooser.getSelectedFile().getAbsolutePath();
        if (!filePath.endsWith(".csv")) {
            filePath += ".csv";
        }

        try (FileWriter csvWriter = new FileWriter(filePath)) {
            TableModel model = jTable1.getModel();

            // Menulis header
            for (int i = 0; i < model.getColumnCount(); i++) {
                csvWriter.append(model.getColumnName(i));
                if (i < model.getColumnCount() - 1) {
                    csvWriter.append(",");
                }
            }
            csvWriter.append("\n");

            // Menulis data
            for (int i = 0; i < model.getRowCount(); i++) {
                for (int j = 0; j < model.getColumnCount(); j++) {
                    Object value = model.getValueAt(i, j);
                    csvWriter.append(value != null ? value.toString() : "");
                    if (j < model.getColumnCount() - 1) {
                        csvWriter.append(",");
                    }
                }
                csvWriter.append("\n");
            }

            csvWriter.flush();
            JOptionPane.showMessageDialog(null, "Data berhasil diekspor ke " + filePath);
        } catch (IOException e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(null, "Terjadi kesalahan saat menyimpan file.", "Error", JOptionPane.ERROR_MESSAGE);
        }
    }
    }//GEN-LAST:event_jButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
