package view;

import controller.Controller;
import model.Petugas;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */

/**
 *
 * @author kevinramadha
 */
public class BLOKIII extends javax.swing.JPanel {
    private Controller controller;
    /**
     * Creates new form BLOKIII
     */
    public BLOKIII(Controller controller) {
        this.controller = controller;
        initComponents();
    }
    
    public void setData(){
        Petugas currentPetugas = controller.getCurrentPetugas();

        if (currentPetugas != null){
            Petugas petugas = controller.getRekapitulasi(currentPetugas.getKodeSubSLS());
            jTextField14.setText(String.valueOf(petugas.getSebelum()));
            jTextField2.setText(String.valueOf(petugas.getSesudah()));
            jTextField3.setText(String.valueOf(petugas.getTanamanPangan()));
            jTextField4.setText(String.valueOf(petugas.getHortikultura()));
            jTextField5.setText(String.valueOf(petugas.getPerkebunan()));
            jTextField6.setText(String.valueOf(petugas.getPeternakan()));
            jTextField7.setText(String.valueOf(petugas.getPerikanan()));
            jTextField8.setText(String.valueOf(petugas.getKehutanan()));
            jTextField9.setText(String.valueOf(petugas.getJasaPertanian()));
            jTextField10.setText(String.valueOf(petugas.getJumlahArtPertanian()));
            jTextField11.setText(String.valueOf(petugas.getJlhRutaPertanian()));
            jTextField12.setText(String.valueOf(petugas.getNoUrutTerbesar()));
            jTextField13.setText(String.valueOf(petugas.getPerkiraanHasil()));
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        blokIII1 = new javax.swing.JLabel();
        jLabel301 = new javax.swing.JLabel();
        jLabel301note = new javax.swing.JLabel();
        jLabel303 = new javax.swing.JLabel();
        jLabel303note = new javax.swing.JLabel();
        jLabel303a = new javax.swing.JLabel();
        jLabel303b = new javax.swing.JLabel();
        jLabel303c = new javax.swing.JLabel();
        jLabel303d = new javax.swing.JLabel();
        jLabel303e = new javax.swing.JLabel();
        jLabel303f = new javax.swing.JLabel();
        jLabel303g = new javax.swing.JLabel();
        jLabel304 = new javax.swing.JLabel();
        jLabel304note = new javax.swing.JLabel();
        jLabel305 = new javax.swing.JLabel();
        jLabel305note = new javax.swing.JLabel();
        NoUrutKeluarTerbesarLabel = new javax.swing.JLabel();
        JumlahPerkiraanKeluargaLabel = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        jTextField4 = new javax.swing.JTextField();
        jTextField5 = new javax.swing.JTextField();
        jTextField6 = new javax.swing.JTextField();
        jTextField7 = new javax.swing.JTextField();
        jTextField8 = new javax.swing.JTextField();
        jTextField9 = new javax.swing.JTextField();
        jTextField10 = new javax.swing.JTextField();
        jTextField11 = new javax.swing.JTextField();
        jTextField12 = new javax.swing.JTextField();
        jTextField13 = new javax.swing.JTextField();
        jLabel306 = new javax.swing.JLabel();
        jTextField14 = new javax.swing.JTextField();

        jPanel1.setBackground(new java.awt.Color(0, 51, 153));

        blokIII1.setFont(new java.awt.Font("Helvetica", 1, 18)); // NOI18N
        blokIII1.setForeground(new java.awt.Color(255, 255, 255));
        blokIII1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        blokIII1.setText("BLOK III. REKAPITULASI");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 872, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(blokIII1, javax.swing.GroupLayout.PREFERRED_SIZE, 682, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 42, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addGap(12, 12, 12)
                    .addComponent(blokIII1)
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        jLabel301.setFont(new java.awt.Font("Arial", 1, 13)); // NOI18N
        jLabel301.setText("302. Jumlah keluarga hasil pemutakhiran");

        jLabel301note.setFont(new java.awt.Font("Arial", 0, 8)); // NOI18N
        jLabel301note.setText("[Disalin dari jumlah hal terakhir Blok VA kolom (5) ditambah jumlah keluarga tambahan pada Blok VB]");

        jLabel303.setFont(new java.awt.Font("Arial", 1, 13)); // NOI18N
        jLabel303.setText("303. Jumlah rumah tangga usaha pertanian menurut subsektor");

        jLabel303note.setFont(new java.awt.Font("Arial", 0, 8)); // NOI18N
        jLabel303note.setText("[Disalin dari Blok VA - VB halaman terakhir Rincian c Kolom (10) s.d Kolom (16)]");

        jLabel303a.setFont(new java.awt.Font("Arial", 0, 13)); // NOI18N
        jLabel303a.setText("a. Subsektor tanaman pangan (Kolom (10))");

        jLabel303b.setFont(new java.awt.Font("Arial", 0, 13)); // NOI18N
        jLabel303b.setText("b. Subsektor hortikultura (Kolom (11))");

        jLabel303c.setFont(new java.awt.Font("Arial", 0, 13)); // NOI18N
        jLabel303c.setText("c. Subsektor perkebunan (Kolom (12))");

        jLabel303d.setFont(new java.awt.Font("Arial", 0, 13)); // NOI18N
        jLabel303d.setText("d.  Subsektor peternakan (Kolom (13))");

        jLabel303e.setFont(new java.awt.Font("Arial", 0, 13)); // NOI18N
        jLabel303e.setText("e. Subsektor perikanan (Kolom (14))");

        jLabel303f.setFont(new java.awt.Font("Arial", 0, 13)); // NOI18N
        jLabel303f.setText("f. Subsektor kehutanan (Kolom (15))");

        jLabel303g.setFont(new java.awt.Font("Arial", 0, 13)); // NOI18N
        jLabel303g.setText("g. Jasa pertanian (Kolom (16))");

        jLabel304.setFont(new java.awt.Font("Arial", 1, 13)); // NOI18N
        jLabel304.setText("304. Jumlah pengelola unit usaha pertanian perorangan");

        jLabel304note.setFont(new java.awt.Font("Arial", 0, 8)); // NOI18N
        jLabel304note.setText("[Disalin dari Blok VA - VB halaman terakhir Rincian c Kolom (18)] ");

        jLabel305.setFont(new java.awt.Font("Arial", 1, 13)); // NOI18N
        jLabel305.setText("305. Jumlah Rumah Tangga Usaha Pertanian");

        jLabel305note.setFont(new java.awt.Font("Arial", 0, 8)); // NOI18N
        jLabel305note.setText("[Disalin dari nomor urut terbesar Blok VA - VB Kolom (19)]");

        NoUrutKeluarTerbesarLabel.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        NoUrutKeluarTerbesarLabel.setText("No. Urut Keluarga Terbesar                                                                                            :");

        JumlahPerkiraanKeluargaLabel.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        JumlahPerkiraanKeluargaLabel.setText("Jumlah perkiraan keluarga pertanian hasil pemutakhiran wilkerstat tahun 2022     :");

        jTextField2.setEditable(false);
        jTextField2.setPreferredSize(new java.awt.Dimension(100, 22));
        jTextField2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField2ActionPerformed(evt);
            }
        });

        jTextField3.setEditable(false);
        jTextField3.setPreferredSize(new java.awt.Dimension(100, 22));

        jTextField4.setEditable(false);
        jTextField4.setPreferredSize(new java.awt.Dimension(100, 22));

        jTextField5.setEditable(false);
        jTextField5.setPreferredSize(new java.awt.Dimension(100, 22));

        jTextField6.setEditable(false);
        jTextField6.setMinimumSize(new java.awt.Dimension(100, 22));
        jTextField6.setPreferredSize(new java.awt.Dimension(100, 22));

        jTextField7.setEditable(false);
        jTextField7.setMinimumSize(new java.awt.Dimension(100, 22));
        jTextField7.setPreferredSize(new java.awt.Dimension(100, 22));

        jTextField8.setEditable(false);
        jTextField8.setMinimumSize(new java.awt.Dimension(100, 22));
        jTextField8.setPreferredSize(new java.awt.Dimension(100, 22));

        jTextField9.setEditable(false);
        jTextField9.setMinimumSize(new java.awt.Dimension(100, 22));
        jTextField9.setPreferredSize(new java.awt.Dimension(100, 22));

        jTextField10.setEditable(false);
        jTextField10.setMinimumSize(new java.awt.Dimension(100, 22));
        jTextField10.setPreferredSize(new java.awt.Dimension(100, 22));

        jTextField11.setEditable(false);
        jTextField11.setMinimumSize(new java.awt.Dimension(100, 22));
        jTextField11.setPreferredSize(new java.awt.Dimension(100, 22));

        jTextField12.setEditable(false);
        jTextField12.setMinimumSize(new java.awt.Dimension(100, 22));
        jTextField12.setPreferredSize(new java.awt.Dimension(100, 22));

        jTextField13.setEditable(false);
        jTextField13.setMinimumSize(new java.awt.Dimension(100, 22));
        jTextField13.setPreferredSize(new java.awt.Dimension(100, 22));

        jLabel306.setFont(new java.awt.Font("Arial", 1, 13)); // NOI18N
        jLabel306.setText("301. Jumlah keluarga sebelum pemutakhiran");

        jTextField14.setEditable(false);
        jTextField14.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField14ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(92, 92, 92)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(4, 4, 4)
                        .addComponent(jLabel304, javax.swing.GroupLayout.PREFERRED_SIZE, 389, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(39, 39, 39)
                        .addComponent(jLabel304note, javax.swing.GroupLayout.PREFERRED_SIZE, 354, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(4, 4, 4)
                        .addComponent(jLabel305, javax.swing.GroupLayout.PREFERRED_SIZE, 389, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(39, 39, 39)
                        .addComponent(jLabel305note, javax.swing.GroupLayout.PREFERRED_SIZE, 354, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(NoUrutKeluarTerbesarLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 560, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                            .addGap(4, 4, 4)
                            .addComponent(JumlahPerkiraanKeluargaLabel)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(jLabel303))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel306, javax.swing.GroupLayout.PREFERRED_SIZE, 389, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(187, 187, 187)
                                .addComponent(jTextField14, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel301, javax.swing.GroupLayout.PREFERRED_SIZE, 389, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(35, 35, 35)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel303b, javax.swing.GroupLayout.PREFERRED_SIZE, 276, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel303c, javax.swing.GroupLayout.PREFERRED_SIZE, 276, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel303d, javax.swing.GroupLayout.PREFERRED_SIZE, 276, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel303e, javax.swing.GroupLayout.PREFERRED_SIZE, 276, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel303f, javax.swing.GroupLayout.PREFERRED_SIZE, 276, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel303g, javax.swing.GroupLayout.PREFERRED_SIZE, 276, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel303a, javax.swing.GroupLayout.PREFERRED_SIZE, 276, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel303note, javax.swing.GroupLayout.PREFERRED_SIZE, 354, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel301note, javax.swing.GroupLayout.PREFERRED_SIZE, 354, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                .addGap(187, 187, 187)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jTextField5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jTextField6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jTextField7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jTextField8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jTextField9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jTextField10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jTextField11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jTextField12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jTextField13, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 19, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addComponent(jTextField14, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel306))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel301)
                        .addGap(6, 6, 6)
                        .addComponent(jLabel301note)))
                .addGap(18, 18, 18)
                .addComponent(jLabel303)
                .addGap(6, 6, 6)
                .addComponent(jLabel303note)
                .addGap(6, 6, 6)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel303a)
                        .addGap(13, 13, 13)
                        .addComponent(jLabel303b)
                        .addGap(13, 13, 13)
                        .addComponent(jLabel303c)
                        .addGap(13, 13, 13)
                        .addComponent(jLabel303d)
                        .addGap(13, 13, 13)
                        .addComponent(jLabel303e)
                        .addGap(13, 13, 13)
                        .addComponent(jLabel303f)
                        .addGap(13, 13, 13)
                        .addComponent(jLabel303g))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextField5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextField6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextField7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextField8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextField9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel304)
                        .addGap(6, 6, 6)
                        .addComponent(jLabel304note))
                    .addComponent(jTextField10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(12, 12, 12)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel305)
                        .addGap(6, 6, 6)
                        .addComponent(jLabel305note))
                    .addComponent(jTextField11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(NoUrutKeluarTerbesarLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jTextField12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextField13, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(JumlahPerkiraanKeluargaLabel))))
                .addGap(65, 65, 65))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField2ActionPerformed

    private void jTextField14ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField14ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField14ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel JumlahPerkiraanKeluargaLabel;
    private javax.swing.JLabel NoUrutKeluarTerbesarLabel;
    private javax.swing.JLabel blokIII1;
    private javax.swing.JLabel jLabel301;
    private javax.swing.JLabel jLabel301note;
    private javax.swing.JLabel jLabel303;
    private javax.swing.JLabel jLabel303a;
    private javax.swing.JLabel jLabel303b;
    private javax.swing.JLabel jLabel303c;
    private javax.swing.JLabel jLabel303d;
    private javax.swing.JLabel jLabel303e;
    private javax.swing.JLabel jLabel303f;
    private javax.swing.JLabel jLabel303g;
    private javax.swing.JLabel jLabel303note;
    private javax.swing.JLabel jLabel304;
    private javax.swing.JLabel jLabel304note;
    private javax.swing.JLabel jLabel305;
    private javax.swing.JLabel jLabel305note;
    private javax.swing.JLabel jLabel306;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField jTextField10;
    private javax.swing.JTextField jTextField11;
    private javax.swing.JTextField jTextField12;
    private javax.swing.JTextField jTextField13;
    private javax.swing.JTextField jTextField14;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JTextField jTextField7;
    private javax.swing.JTextField jTextField8;
    private javax.swing.JTextField jTextField9;
    // End of variables declaration//GEN-END:variables
}
