/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package view;

import controller.Controller;
import javax.swing.JOptionPane;
import model.Ruta;

/**
 *
 * @author Bara
 */
public class BlokV_3 extends javax.swing.JPanel {
    private Controller controller;
    private Ruta rutaTerpilih = new Ruta();

    /**
     * Creates new form BlokV_3
     */
    public BlokV_3(Controller controller) {
        this.controller = controller;
        initComponents();
    }
    
    public void setPertanian(Ruta ruta){
        this.rutaTerpilih = ruta;
        tanamanPangan.setSelectedItem(String.valueOf(rutaTerpilih.getTanamanPangan()));
        hortikultura.setSelectedItem(String.valueOf(rutaTerpilih.getHortikultura()));
        perkebunan.setSelectedItem(String.valueOf(rutaTerpilih.getPerkebunan()));
        peternakan.setSelectedItem(String.valueOf(rutaTerpilih.getPeternakan()));
        perikanan.setSelectedItem(String.valueOf(rutaTerpilih.getPerikanan()));
        kehutanan.setSelectedItem(String.valueOf(rutaTerpilih.getKehutanan()));
        jasaPertanian.setSelectedItem(String.valueOf(rutaTerpilih.getJasaPertanian()));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        blokIII1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        tanamanPangan = new javax.swing.JComboBox<>();
        hortikultura = new javax.swing.JComboBox<>();
        perkebunan = new javax.swing.JComboBox<>();
        peternakan = new javax.swing.JComboBox<>();
        perikanan = new javax.swing.JComboBox<>();
        kehutanan = new javax.swing.JComboBox<>();
        jasaPertanian = new javax.swing.JComboBox<>();

        jPanel1.setBackground(new java.awt.Color(0, 51, 153));

        blokIII1.setFont(new java.awt.Font("Helvetica", 1, 18)); // NOI18N
        blokIII1.setForeground(new java.awt.Color(255, 255, 255));
        blokIII1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        blokIII1.setText("BLOK V. KETERANGAN KELUARGA / RUMAH TANGGA  (10-16)");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(blokIII1, javax.swing.GroupLayout.DEFAULT_SIZE, 897, Short.MAX_VALUE)
                    .addContainerGap()))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 42, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addGap(12, 12, 12)
                    .addComponent(blokIII1)
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        jLabel2.setFont(new java.awt.Font("Helvetica", 1, 13)); // NOI18N
        jLabel2.setText("Apakah ada ART yang memelihara/menguasai/melakukan kegiatan pertanian dengan tujuan sebagian atau");

        jLabel5.setFont(new java.awt.Font("Helvetica", 0, 13)); // NOI18N
        jLabel5.setText("(10)    Tanaman Pangan");

        jLabel6.setFont(new java.awt.Font("Helvetica", 0, 13)); // NOI18N
        jLabel6.setText("(11)    Hortikultura");

        jLabel7.setFont(new java.awt.Font("Helvetica", 0, 13)); // NOI18N
        jLabel7.setText("(12)    Perkebunan");

        jLabel8.setFont(new java.awt.Font("Helvetica", 0, 13)); // NOI18N
        jLabel8.setText("(13)    Peternakan");

        jLabel9.setFont(new java.awt.Font("Helvetica", 0, 13)); // NOI18N
        jLabel9.setText("(14)    Perikanan");

        jLabel10.setFont(new java.awt.Font("Helvetica", 0, 13)); // NOI18N
        jLabel10.setText("(15)    Kehutanan");

        jLabel11.setFont(new java.awt.Font("Helvetica", 0, 13)); // NOI18N
        jLabel11.setText("(16)    Jasa Pertanian");

        jButton1.setBackground(new java.awt.Color(0, 51, 153));
        jButton1.setFont(new java.awt.Font("Helvetica", 0, 13)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Submit");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Helvetica", 1, 13)); // NOI18N
        jLabel3.setText("seluruh hasilnya untuk dijual/ditukar? (Keterangan Ya = 1, Tidak=0)");

        tanamanPangan.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "0", "1" }));

        hortikultura.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "0", "1" }));

        perkebunan.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "0", "1" }));

        peternakan.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "0", "1" }));

        perikanan.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "0", "1" }));

        kehutanan.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "0", "1" }));

        jasaPertanian.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "0", "1" }));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jLabel9, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jLabel8, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 363, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(perkebunan, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(peternakan, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(perikanan, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(kehutanan, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jasaPertanian, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                                .addGroup(layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 363, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(tanamanPangan, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(hortikultura, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 424, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(0, 242, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel2)
                .addGap(8, 8, 8)
                .addComponent(jLabel3)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(tanamanPangan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(hortikultura, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(perkebunan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(peternakan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(perikanan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(kehutanan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(jasaPertanian, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(28, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        
        rutaTerpilih.setTanamanPangan(Integer.parseInt(tanamanPangan.getSelectedItem().toString()));
        rutaTerpilih.setHortikultura(Integer.parseInt(hortikultura.getSelectedItem().toString()));
        rutaTerpilih.setPerkebunan(Integer.parseInt(perkebunan.getSelectedItem().toString()));
        rutaTerpilih.setPeternakan(Integer.parseInt(peternakan.getSelectedItem().toString()));
        rutaTerpilih.setPerikanan(Integer.parseInt(perikanan.getSelectedItem().toString()));
        rutaTerpilih.setKehutanan(Integer.parseInt(kehutanan.getSelectedItem().toString()));
        rutaTerpilih.setJasaPertanian(Integer.parseInt(jasaPertanian.getSelectedItem().toString()));
        
        if(controller.getDataRutaBaru()!=null){
            Ruta rutaBaru = controller.getDataRutaBaru();
            
            rutaBaru.setTanamanPangan(Integer.parseInt(tanamanPangan.getSelectedItem().toString()));
            rutaBaru.setHortikultura(Integer.parseInt(hortikultura.getSelectedItem().toString()));
            rutaBaru.setPerkebunan(Integer.parseInt(perkebunan.getSelectedItem().toString()));
            rutaBaru.setPeternakan(Integer.parseInt(peternakan.getSelectedItem().toString()));
            rutaBaru.setPerikanan(Integer.parseInt(perikanan.getSelectedItem().toString()));
            rutaBaru.setKehutanan(Integer.parseInt(kehutanan.getSelectedItem().toString()));
            rutaBaru.setJasaPertanian(Integer.parseInt(jasaPertanian.getSelectedItem().toString()));
            
            if(tanamanPangan.getSelectedItem().equals("0") && 
            hortikultura.getSelectedItem().equals("0") && 
            perkebunan.getSelectedItem().equals("0") && 
            peternakan.getSelectedItem().equals("0") && 
            perikanan.getSelectedItem().equals("0") && 
            kehutanan.getSelectedItem().equals("0") && 
            jasaPertanian.getSelectedItem().equals("0")){
                controller.setBlokVb(rutaBaru);
                controller.showDaftarRuta();
            }else{
                controller.showBlokV4b(rutaBaru);
            }
            
            
        }else{
            if(tanamanPangan.getSelectedItem().equals("0") && 
            hortikultura.getSelectedItem().equals("0") && 
            perkebunan.getSelectedItem().equals("0") && 
            peternakan.getSelectedItem().equals("0") && 
            perikanan.getSelectedItem().equals("0") && 
            kehutanan.getSelectedItem().equals("0") && 
            jasaPertanian.getSelectedItem().equals("0")){
                controller.setBlokVa(rutaTerpilih);
                controller.showDaftarRuta();
            }else{
                controller.showBlokV4(rutaTerpilih);
            }
        }
    }//GEN-LAST:event_jButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel blokIII1;
    private javax.swing.JComboBox<String> hortikultura;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JComboBox<String> jasaPertanian;
    private javax.swing.JComboBox<String> kehutanan;
    private javax.swing.JComboBox<String> perikanan;
    private javax.swing.JComboBox<String> perkebunan;
    private javax.swing.JComboBox<String> peternakan;
    private javax.swing.JComboBox<String> tanamanPangan;
    // End of variables declaration//GEN-END:variables

}
