/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package view;

import controller.Controller;
import javax.swing.JOptionPane;
import model.Ruta;

/**
 *
 * @author Bara
 */
public class BlokV_4 extends javax.swing.JPanel {
    private Controller controller;
    private Ruta rutaTerpilih = new Ruta();

    /**
     * Creates new form BlokV_4
     */
    public BlokV_4(Controller controller) {
        this.controller = controller;
        initComponents();
    }
    
    public void setRutaPertanian(Ruta ruta){
        this.rutaTerpilih = ruta;
        
        if(rutaTerpilih.getSubsektorUtama()!=null){
            subsektor.setSelectedItem(rutaTerpilih.getSubsektorUtama());
        }else{
            subsektor.setSelectedItem("Pilih subsektor");
        }
        jumlahArtPetani.setText(String.valueOf(rutaTerpilih.getJumlahArtPertanian()));
        if(rutaTerpilih.getUrutRutaPertanian()!=0){
            noRutaPetani.setText(String.valueOf(rutaTerpilih.getUrutRutaPertanian()));
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        blokIII1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jumlahArtPetani = new javax.swing.JTextField();
        noRutaPetani = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        subsektor = new javax.swing.JComboBox<>();

        jPanel1.setBackground(new java.awt.Color(0, 51, 153));

        blokIII1.setFont(new java.awt.Font("Helvetica", 1, 18)); // NOI18N
        blokIII1.setForeground(new java.awt.Color(255, 255, 255));
        blokIII1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        blokIII1.setText("BLOK V. KETERANGAN KELUARGA / RUMAH TANGGA  (17-19)");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(blokIII1, javax.swing.GroupLayout.DEFAULT_SIZE, 667, Short.MAX_VALUE)
                    .addContainerGap()))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 42, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addGap(12, 12, 12)
                    .addComponent(blokIII1)
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        jLabel2.setFont(new java.awt.Font("Helvetica", 0, 13)); // NOI18N
        jLabel2.setText("(17)    Sub sektor  utama:");

        jLabel3.setFont(new java.awt.Font("Helvetica", 0, 13)); // NOI18N
        jLabel3.setText("(18)    Jumlah ART yang memelihara/menguasai/");

        jLabel4.setFont(new java.awt.Font("Helvetica", 0, 13)); // NOI18N
        jLabel4.setText("melakukan kegiatan pertanian?");

        jLabel5.setFont(new java.awt.Font("Helvetica", 0, 13)); // NOI18N
        jLabel5.setText("(19)    Isikan nomor urut rumah tangga usaha pertanian");

        jLabel6.setFont(new java.awt.Font("Helvetica", 0, 13)); // NOI18N

        jButton1.setBackground(new java.awt.Color(0, 51, 153));
        jButton1.setFont(new java.awt.Font("Helvetica", 0, 13)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Submit");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        subsektor.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Pilih subsektor", "Tanaman Pangan", "Hortikultura", "Perkebunan", "Peternakan", "Perikanan", "Kehutanan", "Jasa Pertanian" }));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(18, 18, 18))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel5)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jLabel6))
                                    .addComponent(jLabel3)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(38, 38, 38)
                                        .addComponent(jLabel4)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 114, Short.MAX_VALUE)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jumlahArtPetani, javax.swing.GroupLayout.DEFAULT_SIZE, 177, Short.MAX_VALUE)
                            .addComponent(noRutaPetani)
                            .addComponent(subsektor, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addGap(48, 48, 48))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(subsektor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jumlahArtPetani, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel4)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(noRutaPetani, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addGap(25, 25, 25)
                            .addComponent(jLabel6))
                        .addGroup(layout.createSequentialGroup()
                            .addGap(18, 18, 18)
                            .addComponent(jLabel5))))
                .addGap(36, 36, 36)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(46, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        if(jumlahArtPetani.getText().isEmpty() || noRutaPetani.getText().isEmpty() || subsektor.getSelectedItem().equals("Pilih subsektor")){
            JOptionPane.showMessageDialog(this, "Semua data harus terisi!", "Pesan", JOptionPane.WARNING_MESSAGE);
            return;
        }else{
            if(isNotInteger(jumlahArtPetani.getText())){
                JOptionPane.showMessageDialog(this, "Form no.(18) harus berupa angka!", "Pesan", JOptionPane.WARNING_MESSAGE);
                return;
            }
            if(isNotInteger(noRutaPetani.getText())){
                JOptionPane.showMessageDialog(this, "Form no.(19) harus berupa angka!", "Pesan", JOptionPane.WARNING_MESSAGE);
                return;
            }
            
            rutaTerpilih.setSubsektorUtama(subsektor.getSelectedItem().toString());
            rutaTerpilih.setJumlahArtPertanian(Integer.parseInt(jumlahArtPetani.getText()));
            rutaTerpilih.setUrutRutaPertanian(Integer.parseInt(noRutaPetani.getText()));
            
            if(controller.getDataRutaBaru()!=null){    
                Ruta rutaBaru = controller.getDataRutaBaru();
                rutaBaru.setSubsektorUtama(subsektor.getSelectedItem().toString());
                rutaBaru.setJumlahArtPertanian(Integer.parseInt(jumlahArtPetani.getText()));
                rutaBaru.setUrutRutaPertanian(Integer.parseInt(noRutaPetani.getText()));
                
                controller.setBlokVb(rutaBaru);
                controller.showDaftarRuta();
            }else{
                controller.setBlokVa(rutaTerpilih);
                controller.showDaftarRuta();
            }
        }
    }//GEN-LAST:event_jButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel blokIII1;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField jumlahArtPetani;
    private javax.swing.JTextField noRutaPetani;
    private javax.swing.JComboBox<String> subsektor;
    // End of variables declaration//GEN-END:variables
    
    public boolean isNotInteger(String text) {
        try {
            Integer.parseInt(text);
            return false;
        } catch (NumberFormatException e) {
            return true;
        }
    }
}
