package view;

import controller.Controller;
import database.DatabasePetugas;
import java.awt.event.ActionEvent;
import java.sql.SQLException;
import java.util.List;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import model.*;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */

/**
 *
 * @author kevinramadha
 */
public class Insert extends javax.swing.JPanel {
    private Controller controller;
    /**
     * Creates new form Insert
     */
    public Insert(Controller controller) {
        this.controller = controller;
        initComponents();
        initListeners();
        loadProvinsiComboBox();
    }
    
    private void initListeners() {
        provinsiComboBox.addActionListener((ActionEvent e) -> updateKabupatenComboBox());
        kabupatenComboBox.addActionListener((ActionEvent e) -> updateKecamatanComboBox());
        kecamatanComboBox.addActionListener((ActionEvent e) -> updateDesaComboBox());
    }
    
    private void updateKabupatenComboBox() {
        String selectedProvinsi = (String) provinsiComboBox.getSelectedItem();
        if (selectedProvinsi != null) {
            try {
                DatabasePetugas dbPetugas = new DatabasePetugas();
                String idProvinsi = dbPetugas.getIdProvinsiByName(selectedProvinsi);
                List<String> kabupatenList = DatabasePetugas.getKabupatenByProvinsi(idProvinsi);
                kabupatenComboBox.setModel(new DefaultComboBoxModel<>(kabupatenList.toArray(new String[0])));
            } catch (SQLException ex) {
                JOptionPane.showMessageDialog(this, "Error retrieving data from database: " + ex.getMessage(), "Database Error", JOptionPane.ERROR_MESSAGE);
            }
        }
    }
    
    private void updateKecamatanComboBox() {
        String selectedKabupaten = (String) kabupatenComboBox.getSelectedItem();
        if (selectedKabupaten != null) {
            try {
                DatabasePetugas dbPetugas = new DatabasePetugas();
                String idKabupaten = dbPetugas.getIdKabupatenByName(selectedKabupaten);
                List<String> kecamatanList = DatabasePetugas.getKecamatanByKabupaten(idKabupaten);
                kecamatanComboBox.setModel(new DefaultComboBoxModel<>(kecamatanList.toArray(new String[0])));
            } catch (SQLException ex) {
                JOptionPane.showMessageDialog(this, "Error retrieving data from database: " + ex.getMessage(), "Database Error", JOptionPane.ERROR_MESSAGE);
            }
        }
    }
    
    private void loadProvinsiComboBox() {
        try {
            List<String> provinsiList = DatabasePetugas.getAllProvinsi();
            provinsiComboBox.setModel(new DefaultComboBoxModel<>(provinsiList.toArray(new String[0])));
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(this, "Error loading provinsi data: " + ex.getMessage(), "Database Error", JOptionPane.ERROR_MESSAGE);
        }
    }
    
    private void updateDesaComboBox() {
        String selectedKecamatan = (String) kecamatanComboBox.getSelectedItem();
        if (selectedKecamatan != null) {
            try {
                DatabasePetugas dbPetugas = new DatabasePetugas();
                String idKecamatan = dbPetugas.getIdKecamatanByName(selectedKecamatan);
                List<String> desaList = DatabasePetugas.getDesaByKecamatan(idKecamatan);
                desaComboBox.setModel(new DefaultComboBoxModel<>(desaList.toArray(new String[0])));
            } catch (SQLException ex) {
                JOptionPane.showMessageDialog(this, "Error retrieving data from database: " + ex.getMessage(), "Database Error", JOptionPane.ERROR_MESSAGE);
            }
        }
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        AdminPanel = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        MenuPanel = new javax.swing.JPanel();
        InsertButton2 = new javax.swing.JButton();
        tambahButton = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();
        viewButton = new javax.swing.JButton();
        LogoutButton = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        kodeField = new javax.swing.JTextField();
        namaField = new javax.swing.JTextField();
        provinsiComboBox = new javax.swing.JComboBox<>();
        kabupatenComboBox = new javax.swing.JComboBox<>();
        kecamatanComboBox = new javax.swing.JComboBox<>();
        desaComboBox = new javax.swing.JComboBox<>();
        jLabel11 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        kodeSLSField = new javax.swing.JTextField();
        namaSLSField = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        subSLSField = new javax.swing.JTextField();

        AdminPanel.setBackground(new java.awt.Color(0, 51, 153));

        jLabel2.setBackground(new java.awt.Color(51, 102, 255));
        jLabel2.setFont(new java.awt.Font("Helvetica Neue", 1, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("ADMIN DASHBOARD");

        javax.swing.GroupLayout AdminPanelLayout = new javax.swing.GroupLayout(AdminPanel);
        AdminPanel.setLayout(AdminPanelLayout);
        AdminPanelLayout.setHorizontalGroup(
            AdminPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(AdminPanelLayout.createSequentialGroup()
                .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 732, Short.MAX_VALUE)
                .addContainerGap())
        );
        AdminPanelLayout.setVerticalGroup(
            AdminPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 68, Short.MAX_VALUE)
        );

        MenuPanel.setBackground(new java.awt.Color(0, 51, 153));

        InsertButton2.setText("Insert/Save");
        InsertButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                InsertButton2ActionPerformed(evt);
            }
        });

        tambahButton.setText("Tambahkan Ruta");
        tambahButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tambahButtonActionPerformed(evt);
            }
        });

        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/projectkelompok3/Logo (4).png"))); // NOI18N

        viewButton.setText("View");
        viewButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewButtonActionPerformed(evt);
            }
        });

        LogoutButton.setText("Logout");
        LogoutButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LogoutButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout MenuPanelLayout = new javax.swing.GroupLayout(MenuPanel);
        MenuPanel.setLayout(MenuPanelLayout);
        MenuPanelLayout.setHorizontalGroup(
            MenuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MenuPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(MenuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(InsertButton2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(tambahButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(viewButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(LogoutButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
            .addGroup(MenuPanelLayout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(jLabel12)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        MenuPanelLayout.setVerticalGroup(
            MenuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MenuPanelLayout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(57, 57, 57)
                .addComponent(InsertButton2)
                .addGap(18, 18, 18)
                .addComponent(tambahButton)
                .addGap(18, 18, 18)
                .addComponent(viewButton)
                .addGap(18, 18, 18)
                .addComponent(LogoutButton)
                .addContainerGap(224, Short.MAX_VALUE))
        );

        jLabel1.setFont(new java.awt.Font("Helvetica Neue", 1, 20)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("IDENTITAS PETUGAS");

        jLabel3.setText("Kode");

        jLabel4.setText("Nama Petugas");

        jLabel6.setText("Tempat Bertugas                                   :");

        jLabel7.setText("Provinsi");

        jLabel8.setText("Kabupaten/kota");

        jLabel9.setText("Kecamatan");

        jLabel10.setText("Desa/Kelurahan");

        kodeField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kodeFieldActionPerformed(evt);
            }
        });

        provinsiComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Nanggroe Aceh Darussalam", "Sumatera Utara", "Sumatera Selatan", "Sumatera Barat", "Bengkulu", "Riau", "Kepulauan Riau", "Jambi", "Lampung", "Bangka Belitung", "Kalimantan Barat", "Kalimantan Timur", "Kalimantan Selatan", "Kalimantan Tengah", "Kalimantan Utara", "Banten", "DKI Jakarta", "Jawa Barat", "Jawa Tengah", "Daerah Istimewa Yogyakarta", "Jawa Timur", "Bali", "Nusa Tenggara Timur", "Nusa Tenggara Barat", "Gorontalo", "Sulawesi Barat", "Sulawesi Tengah", "Sulawesi Utara", "Sulawesi Tenggara", "Sulawesi Selatan", "Maluku Utara", "Maluku", "Papua Barat", "Papua", "Papua Tengah", "Papua Pegunungan", "Papua Selatan", "Papua Barat Daya" }));

        desaComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                desaComboBoxActionPerformed(evt);
            }
        });

        jLabel11.setText("Kode SLS");

        jLabel13.setText("Nama SLS");

        kodeSLSField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kodeSLSFieldActionPerformed(evt);
            }
        });

        namaSLSField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                namaSLSFieldActionPerformed(evt);
            }
        });

        jLabel14.setText("Sub SLS");

        subSLSField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                subSLSFieldActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(MenuPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(AdminPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 146, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                            .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 246, Short.MAX_VALUE))
                                        .addGap(18, 18, 18)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(kodeField, javax.swing.GroupLayout.DEFAULT_SIZE, 322, Short.MAX_VALUE)
                                            .addComponent(namaField)))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 246, Short.MAX_VALUE))
                                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(jLabel13)
                                                        .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                                .addGap(18, 18, 18))
                                            .addGroup(layout.createSequentialGroup()
                                                .addGap(31, 31, 31)
                                                .addComponent(jLabel14)
                                                .addGap(190, 190, 190)))
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(subSLSField)
                                            .addComponent(provinsiComboBox, 0, 322, Short.MAX_VALUE)
                                            .addComponent(kabupatenComboBox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(kecamatanComboBox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(desaComboBox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(kodeSLSField)
                                            .addComponent(namaSLSField, javax.swing.GroupLayout.Alignment.TRAILING))))))
                        .addContainerGap())))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(MenuPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addComponent(AdminPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(kodeField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(namaField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(provinsiComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(kabupatenComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(kecamatanComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(desaComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(kodeSLSField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(namaSLSField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14)
                    .addComponent(subSLSField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void kodeFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kodeFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_kodeFieldActionPerformed

    private void InsertButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_InsertButton2ActionPerformed
        // TODO add your handling code here:
        String kode = kodeField.getText();
        String nama = namaField.getText();
        String namaProvinsi = (String) provinsiComboBox.getSelectedItem();
        String namaKabupaten = (String) kabupatenComboBox.getSelectedItem();
        String namaKecamatan = (String) kecamatanComboBox.getSelectedItem();
        String namaDesa = (String) desaComboBox.getSelectedItem();
        String kodeSLS = kodeSLSField.getText();
        String namaSLS = namaSLSField.getText();
        String kodeSubSLS = subSLSField.getText();
        
        if (kode.isEmpty() || nama.isEmpty() || namaProvinsi.isEmpty() || namaKabupaten.isEmpty() || namaKecamatan.isEmpty() || namaDesa.isEmpty() || kodeSLS.isEmpty() || namaSLS.isEmpty() || kodeSubSLS.isEmpty()) {
            javax.swing.JOptionPane.showMessageDialog(this, "Harap isi semua field dengan benar!", "Warning", javax.swing.JOptionPane.WARNING_MESSAGE);
            return;
        }
        
        if (kode.length() > 20 || kodeSLS.length() > 14 || kodeSubSLS.length() > 16) {
            JOptionPane.showMessageDialog(this, "Panjang kode, kodeSLS, atau kodeSubSLS melebihi batas maksimal!", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }
        
        try{
            DatabasePetugas dbPetugas = new DatabasePetugas();
            String idDesa = dbPetugas.getIdDesaByName(namaDesa);
            kodeSLS = idDesa + kodeSLS;
            kodeSubSLS = kodeSLS + kodeSubSLS;
            
            Petugas petugas = new Petugas();
            petugas.setKode(kode);
            petugas.setNama(nama);
            petugas.setNamaProvinsi(namaProvinsi);
            petugas.setNamaKabupaten(namaKabupaten);
            petugas.setNamaKecamatan(namaKecamatan);
            petugas.setNamaDesa(namaDesa);
            petugas.setKodeSLS(kodeSLS);
            petugas.setNamaSLS(namaSLS);
            petugas.setKodeSubSLS(kodeSubSLS);
           
            boolean success = controller.addPetugas(petugas);
            if (success) {
                javax.swing.JOptionPane.showMessageDialog(this, "Petugas berhasil ditambahkan!", "Success", javax.swing.JOptionPane.INFORMATION_MESSAGE);
                clearForm();
            }
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, "Error inserting petugas: " + ex.getMessage(), "Database Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_InsertButton2ActionPerformed

    private void clearForm() {
        kodeField.setText("");
        namaField.setText("");
        provinsiComboBox.setSelectedIndex(0);
        kodeSLSField.setText("");
        namaSLSField.setText("");
        subSLSField.setText("");
    }
    
    private void viewButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewButtonActionPerformed
        // TODO add your handling code here:
        controller.showViewAdmin();
    }//GEN-LAST:event_viewButtonActionPerformed

    private void tambahButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tambahButtonActionPerformed
        // TODO add your handling code here:
        controller.showPilihTempat();
    }//GEN-LAST:event_tambahButtonActionPerformed

    private void LogoutButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LogoutButtonActionPerformed
        // TODO add your handling code here:
        controller.logout();
    }//GEN-LAST:event_LogoutButtonActionPerformed

    private void kodeSLSFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kodeSLSFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_kodeSLSFieldActionPerformed

    private void namaSLSFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_namaSLSFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_namaSLSFieldActionPerformed

    private void subSLSFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_subSLSFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_subSLSFieldActionPerformed

    private void desaComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_desaComboBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_desaComboBoxActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel AdminPanel;
    private javax.swing.JButton InsertButton2;
    private javax.swing.JButton LogoutButton;
    private javax.swing.JPanel MenuPanel;
    private javax.swing.JComboBox<String> desaComboBox;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JComboBox<String> kabupatenComboBox;
    private javax.swing.JComboBox<String> kecamatanComboBox;
    private javax.swing.JTextField kodeField;
    private javax.swing.JTextField kodeSLSField;
    private javax.swing.JTextField namaField;
    private javax.swing.JTextField namaSLSField;
    private javax.swing.JComboBox<String> provinsiComboBox;
    private javax.swing.JTextField subSLSField;
    private javax.swing.JButton tambahButton;
    private javax.swing.JButton viewButton;
    // End of variables declaration//GEN-END:variables
}
