package view;

import controller.*;
import database.DatabaseConnection;
import java.sql.Connection;
import java.sql.SQLException;
import javax.swing.JMenu;
import javax.swing.JMenuItem;
import javax.swing.JPanel;
import javax.swing.SwingUtilities;
import model.*;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author kevinramadha
 */
public class MainFrame extends javax.swing.JFrame {
    private Controller controller;

    /**
     * Creates new form Admin
     */
    public MainFrame(Controller controller) {
        this.controller = controller;
        initComponents();
    }

    public void setContentPanel(JPanel panel) {
        content.setViewportView(panel);
        
        if (panel instanceof Login) {
            setJMenuBar(null);
        } else if  (panel instanceof Insert){
            setJMenuBar(null);
        } else if  (panel instanceof InsertRuta){
            setJMenuBar(null);
        } else if  (panel instanceof InsertRuta_2){
            setJMenuBar(null);
        } else if  (panel instanceof ViewAdmin){
            setJMenuBar(null);
        }else {
            setJMenuBar(jMenuBar1);
        }

        revalidate();
        repaint();
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        content = new javax.swing.JScrollPane();
        jMenuBar1 = new javax.swing.JMenuBar();
        menu = new javax.swing.JMenu();
        menu1 = new javax.swing.JMenuItem();
        menuBlokI = new javax.swing.JMenu();
        blokI = new javax.swing.JMenuItem();
        menuBlokII = new javax.swing.JMenu();
        blokII = new javax.swing.JMenuItem();
        menuBlokIII = new javax.swing.JMenu();
        blokIII = new javax.swing.JMenuItem();
        menuBlokIV = new javax.swing.JMenu();
        blokIV = new javax.swing.JMenuItem();
        menuBlokV = new javax.swing.JMenu();
        blokV = new javax.swing.JMenuItem();
        jMenuItem13 = new javax.swing.JMenuItem();
        menuLogout = new javax.swing.JMenu();
        jMenuItem2 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocation(new java.awt.Point(180, 60));
        setResizable(false);

        jMenuBar1.setBackground(new java.awt.Color(0, 51, 153));
        jMenuBar1.setForeground(new java.awt.Color(255, 255, 255));
        jMenuBar1.setOpaque(true);

        menu.setText("Home");

        menu1.setText("Home");
        menu1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menu1ActionPerformed(evt);
            }
        });
        menu.add(menu1);

        jMenuBar1.add(menu);

        menuBlokI.setText("Blok I");

        blokI.setText("Keterangan Tempat");
        blokI.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                blokIActionPerformed(evt);
            }
        });
        menuBlokI.add(blokI);

        jMenuBar1.add(menuBlokI);

        menuBlokII.setText("Blok II");

        blokII.setText("Keterangan Petugas");
        blokII.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                blokIIActionPerformed(evt);
            }
        });
        menuBlokII.add(blokII);

        jMenuBar1.add(menuBlokII);

        menuBlokIII.setText("Blok III");

        blokIII.setText("Rekapitulasi");
        blokIII.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                blokIIIActionPerformed(evt);
            }
        });
        menuBlokIII.add(blokIII);

        jMenuBar1.add(menuBlokIII);

        menuBlokIV.setText("Blok IV");

        blokIV.setText("Catatan");
        blokIV.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                blokIVActionPerformed(evt);
            }
        });
        menuBlokIV.add(blokIV);

        jMenuBar1.add(menuBlokIV);

        menuBlokV.setText("BLOK V");

        blokV.setText("Daftar Ruta");
        blokV.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                blokVActionPerformed(evt);
            }
        });
        menuBlokV.add(blokV);

        jMenuItem13.setText("Tambahkan Ruta");
        jMenuItem13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem13ActionPerformed(evt);
            }
        });
        menuBlokV.add(jMenuItem13);

        jMenuBar1.add(menuBlokV);

        menuLogout.setText("Logout");
        menuLogout.setMargin(new java.awt.Insets(3, 10, 3, 6));

        jMenuItem2.setText("Logout");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        menuLogout.add(jMenuItem2);

        jMenuBar1.add(menuLogout);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(content, javax.swing.GroupLayout.PREFERRED_SIZE, 890, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(content, javax.swing.GroupLayout.PREFERRED_SIZE, 526, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void blokIIActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_blokIIActionPerformed
        // TODO add your handling code here:
        controller.showKeteranganPetugas();
    }//GEN-LAST:event_blokIIActionPerformed

    private void blokVActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_blokVActionPerformed
        // TODO add your handling code here:
        controller.showDaftarRuta();
    }//GEN-LAST:event_blokVActionPerformed

    private void jMenuItem13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem13ActionPerformed
        // TODO add your handling code here:
        controller.showRutaBaru();
    }//GEN-LAST:event_jMenuItem13ActionPerformed

    private void blokIActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_blokIActionPerformed
        // TODO add your handling code here:
        controller.showKeteranganTempat();
    }//GEN-LAST:event_blokIActionPerformed

    private void menu1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menu1ActionPerformed
        // TODO add your handling code here:
        controller.showHomePanel();
    }//GEN-LAST:event_menu1ActionPerformed

    private void blokIIIActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_blokIIIActionPerformed
        // TODO add your handling code here:
        controller.showRekapitulasi();
    }//GEN-LAST:event_blokIIIActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        // TODO add your handling code here:
        controller.logout();
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void blokIVActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_blokIVActionPerformed
        // TODO add your handling code here:
        controller.showCatatan();
    }//GEN-LAST:event_blokIVActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        SwingUtilities.invokeLater(new Runnable() {
            @Override
            public void run() {
                Controller controller = new Controller();
                MainFrame mainFrame = new MainFrame(controller);
                mainFrame.setVisible(true);
                controller.start(mainFrame);
                
                try {
                    DatabaseConnection db = new DatabaseConnection();
                    Connection conn = db.getConnection();
                    System.out.println("Connection successful: " + (conn != null));
                    conn.close();
                } catch (SQLException e) {
                    e.printStackTrace();
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem blokI;
    private javax.swing.JMenuItem blokII;
    private javax.swing.JMenuItem blokIII;
    private javax.swing.JMenuItem blokIV;
    private javax.swing.JMenuItem blokV;
    private javax.swing.JScrollPane content;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem13;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenu menu;
    private javax.swing.JMenuItem menu1;
    private javax.swing.JMenu menuBlokI;
    private javax.swing.JMenu menuBlokII;
    private javax.swing.JMenu menuBlokIII;
    private javax.swing.JMenu menuBlokIV;
    private javax.swing.JMenu menuBlokV;
    private javax.swing.JMenu menuLogout;
    // End of variables declaration//GEN-END:variables
    
//    public JMenu getMenu(){
//        return menu;
//    }
//    
//    public JMenu getMenuBlokI(){
//        return menuBlokI;
//    }
//    
//    public JMenu getMenuBlokII(){
//        return menuBlokII;
//    }
//    
//    public JMenu getMenuBlokIII(){
//        return menuBlokIII;
//    }
//    
//    public JMenu getMenuBlokIV(){
//        return menuBlokIV;
//    }
//    
//    public JMenu getMenuBlokV(){
//        return menuBlokV;
//    }
//    
//    public JMenu getMenuLogout(){
//        return menuLogout;
//    }
//    
//    public JMenuItem getBlokI(){
//        return blokI;
//    }
//    
//    public JMenuItem getBlokII(){
//        return blokII;
//    }
//    
//    public JMenuItem getBlokIII(){
//        return blokIII;
//    }
//    
//    public JMenuItem getBlokIV(){
//        return blokIV;
//    }
//    
//    public JMenuItem getBlokV(){
//        return blokV;
//    }
//    
//    public JMenuItem getLogout(){
//        return menuLogout;
//    }
//    
//    public void setContent(JPanel content) {
//        this.content.setViewportView(content);
//    }
}
